import img from 'assets/img/common/propertyImg.svg';

const properties = [
  {
    id: 1,
    like: true,
    type: '원룸',
    priceType: '월세',
    deposit: 100000,
    price: 1000000,
    maintenanceFee: 50,
    address: '서울시 관악구 신림동 123-123',
    propertyName: 'OO 부동산',
    imageUrl: img,
    kokList: true,
  },
  {
    id: 2,
    like: false,
    type: '투룸',
    priceType: '전세',
    deposit: 10000000,
    price: 0,
    maintenanceFee: 0,
    address: '서울시 관악구 신림동 123-124',
    propertyName: 'OO 부동산',
    imageUrl: img,
    kokList: true,
  },
  {
    id: 3,
    like: true,
    type: '원룸',
    priceType: '월세',
    deposit: 1000000,
    price: 200000,
    maintenanceFee: 50,
    address: '서울시 관악구 신림동 123-125',
    propertyName: 'OO 부동산',
    imageUrl: null,
    kokList: false,
  },
  {
    id: 4,
    like: true,
    type: '원룸',
    priceType: '월세',
    deposit: 1000000000000,
    price: 20000,
    maintenanceFee: 50,
    address: '서울시 관악구 신림동 123-125',
    propertyName: 'OO 부동산',
    imageUrl: null,
    kokList: false,
  },
  {
    id: 5,
    like: true,
    type: '원룸',
    priceType: '월세',
    deposit: 10000000,
    price: 220000,
    maintenanceFee: 50,
    address: '서울시 관악구 신림동 123-125',
    propertyName: 'OO 부동산',
    imageUrl: null,
    kokList: true,
  },
  {
    id: 6,
    like: true,
    type: '원룸',
    priceType: '월세',
    deposit: 9900000,
    price: 2000000,
    maintenanceFee: 50,
    address: '서울시 관악구 신림동 123-125',
    propertyName: 'OO 부동산',
    imageUrl: null,
    kokList: false,
  },
  {
    id: 7,
    like: true,
    type: '원룸',
    priceType: '월세',
    deposit: 15200000000,
    price: 200000,
    maintenanceFee: 50,
    address: '서울시 관악구 신림동 123-125',
    propertyName: 'OO 부동산',
    imageUrl: null,
    kokList: true,
  },
];

export default properties;
